### PR TITLE
Added 'expires' parameters and the creation of a recast risks rule for all assets

### LINKED ISSUE #859: [Tenable SC] Support for 'expires' parameter in Recast Risk rules
**Is your feature request related to a problem? Please describe.**
As of now, we can't set expiration for recast risk rules in pyTenable even if the [API](https://docs.tenable.com/security-center/api/Recast-Risk-Rule.htm) supports it.

**Describe the solution you'd like**
pyTenable should allow expiration date for recast risk rules.

**Describe alternatives you've considered**
We have automated this using direct API calls but wanted to ensure a more sustainable model for the broader community.

**Additional context**
N/A

### LINKED ISSUE #860: [Tenable SC] Support for recask risk rules assigned to all hosts
**Is your feature request related to a problem? Please describe.**
As of now, we can't create a recast risk rule in pyTenable targeting all hosts even if the [API](https://docs.tenable.com/security-center/api/Recast-Risk-Rule.htm) supports it.

**Describe the solution you'd like**
pyTenable should allow the creation of recast risk rules targeting all hosts.

**Describe alternatives you've considered**
 We have automated this using direct API calls but wanted to ensure a more sustainable model for the broader community.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jonathan-guihard**
# Description

Added `expires` parameters for recast risks rule creation. 
In addition, when none of `ips`, `uuids`, `asset_list`, or `host_uuids` are specified, the recast risk rule will be applied to all hosts.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

- [X] Tested against Tenable SC directly

**Test Configuration**:
* Python Version(s) Tested: 3.13
* Tenable.sc version (if necessary): 6.4.5

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

resolves #859, resolves #860

### CODE REVIEW

**Comment by jonathan-guihard** [comment]
@SteveMcGrath I was not able to reproduce the pipeline error. Could you please assist?

```
=================================== FAILURES ===================================
________________________ test_recast_risks_list_success ________________________

security_center = <tenable.sc.TenableSC object at 0x7f910bde7b50>

    @pytest.mark.vcr()
    def test_recast_risks_list_success(security_center):
        """
        test recast risks list for success
        """
        resp = security_center.recast_risks.list()
        assert isinstance(resp, list)
        risk = resp[0]
        check(risk, 'id', str)
        check(risk, 'hostType', str)
        check(risk, 'hostValue', str)
        check(risk, 'port', str)
        check(risk, 'protocol', str)
>       check(risk, 'expires', str)

tests/sc/test_recast_risks.py:196: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

i = {'hostType': 'ip', 'hostValue': '127.0.0.1', 'id': '1', 'newSeverity': '0', ...}
name = 'expires', val_type = <class 'str'>, allow_none = False

    def check(i, name, val_type, allow_none=False):
>       assert name in i
E       AssertionError

tests/checker.py:6: AssertionError
_______________________ test_recast_risks_create_success _______________________

arisk = {'comments': '', 'createdTime': '1554731789', 'hostType': 'ip', 'hostValue': '127.0.0.1', ...}

    @pytest.mark.vcr()
    def test_recast_risks_create_success(arisk):
        """
        test recast risks create for success
        """
        assert isinstance(arisk, dict)
        check(arisk, 'id', str)
        check(arisk, 'hostType', str)
        check(arisk, 'hostValue', str)
        check(arisk, 'port', str)
        check(arisk, 'protocol', str)
        check(arisk, 'comments', str)
>       check(arisk, 'expires', str)

tests/sc/test_recast_risks.py:250: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

i = {'comments': '', 'createdTime': '1554731789', 'hostType': 'ip', 'hostValue': '127.0.0.1', ...}
name = 'expires', val_type = <class 'str'>, allow_none = False

    def check(i, name, val_type, allow_none=False):
>       assert name in i
E       AssertionError

tests/checker.py:6: AssertionError
______________________ test_recast_risks_details_success _______________________

security_center = <tenable.sc.TenableSC object at 0x7f910bde7b50>
arisk = {'comments': '', 'createdTime': '1554731789', 'hostType': 'ip', 'hostValue': '127.0.0.1', ...}

    @pytest.mark.vcr()
    def test_recast_risks_details_success(security_center, arisk):
        """
        test recast risks details for success
        """
        risk = security_center.recast_risks.details(int(arisk['id']))
        check(risk, 'id', str)
        check(risk, 'hostType', str)
        check(risk, 'hostValue', str)
        check(risk, 'port', str)
        check(risk, 'protocol', str)
        check(risk, 'comments', str)
>       check(risk, 'expires', str)

tests/sc/test_recast_risks.py:284: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

i = {'comments': '', 'createdTime': '1554731791', 'hostType': 'ip', 'hostValue': '127.0.0.1', ...}
name = 'expires', val_type = <class 'str'>, allow_none = False

    def check(i, name, val_type, allow_none=False):
>       assert name in i
E       AssertionError

tests/checker.py:6: AssertionError
=============================== warnings summary ===============================
```

I've tried it locally and as we can see, `expires` type is `str`. 
```python3
>>> import os
>>> from tenable.sc import TenableSC
>>> sc = TenableSC(os.environ["tenableHost"], access_key=os.environ["TENABLE_CREDS_USR"], secret_key=os.environ["TENABLE_CREDS_PSW"])
<python-input-10>:1: DeprecationWarning: The "host", "port", and "scheme" parameters are deprecated and will be removed from the TenableSC class in version 2.0.
  sc = TenableSC(os.environ["tenableHost"], access_key=os.environ["TENABLE_CREDS_USR"], secret_key=os.environ["TENABLE_CREDS_PSW"])
>>> sc.recast_risks.create(19506, [1], 0, ips=['127.0.0.1'])
{'id': '2127', 'newSeverity': '0', 'hostType': 'ip', 'hostValue': '127.0.0.1', 'port': 'any', 'protocol': 'any', 'comments': '', 'order': '784', 'status': '0', 'expires': '-1', 'createdTime': '1734087480', ...}
>>> rr = sc.recast_risks.create(19506, [1], 0, ips=['127.0.0.1'])
>>> type(rr["expires"])
<class 'str'>
>>> print(rr["expires"])
-1
>>> rr_detail = sc.recast_risks.details(rr["id"])
>>> print(f"{rr_detail['expires']} - {type(rr_detail['expires'])}")
-1 - <class 'str'>
```

Python version: Python 3.13.1
Tenable SC Version: 6.5.1

**Comment by SteveMcGrath** [comment]
So im willing to bet that the reason for the failure is that the test is using an old vcr cassette that doesn't have the field.

You have 2 choices to get it to pass.  either you can manually add the field into the existing cassettes (their named the name of the test within the cassettes folder) OR you can record a new cassette.

I'd argue that the simpler option is to just modify the old cassettes.

Also yes, i know these cassettes are highly annoying, and its one of our longer-term goals to modernize both the test suite and the codebase as well.

Here are the cassettes:

https://github.com/tenable/pyTenable/blob/main/tests/sc/cassettes/test_recast_risks_create_success.yaml
https://github.com/tenable/pyTenable/blob/main/tests/sc/cassettes/test_recast_risks_details_success.yaml
https://github.com/tenable/pyTenable/blob/main/tests/sc/cassettes/test_recast_risks_list_success.yaml

**Comment by jonathan-guihard** [comment]
Indeed, you are right, I missed this part ..
Thanks! The test should be working now

**Review by SteveMcGrath — APPROVED** [review]

**Comment by SteveMcGrath** [comment]
Everything looks good!  the code matches the APIs, everything looks good!  awesome work my man

**Pull request merged**
