### PR TITLE
IN-416

### PR DESCRIPTION
**Pull request by tushar-balwani**
# Description

fixed keyerror in test_scan_results of io test_scans

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested: 3.8.6
* Tenable.sc version (if necessary):

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by mvalliammal — COMMENTED** [review]
Naming conventions in the functions name, can you please change
why test_scan_import_scan?
why cant it be test_import_scan?
Same with all test_scan_import functions

**Comment by dheerajrp** [comment]
Naming conventions is followed according to the standards in the test cases.

**Comment by dheerajrp** [comment]
changes looks good

**Comment by tushar-balwani** [comment]
closing this PR as this PR changes is implemented in #434

**Pull request closed without merging**
