### PR TITLE
update allowed value of cisco privilege escalation

### LINKED ISSUE #618: Error when setting Tenable.sc Credentials with Cisco privilege escalation
**Describe the bug**
The pyTenable Tenable.sc Credentials API (and the Tenable.sc docs) have the incorrect value listed for Cisco privilege escalation. Trying to set the privilege escalation with the suggested `sc.credentials.edit("1000001", privilege_escalation="cisco")` results in an error from the API: "Map not found for privilegeEscalation 'cisco'.

**To Reproduce**
using pyTenable 4.1.7 with Tenable.sc 5.19:
1. Establish an authenticated Tenable.sc session
2. Create a credential entry
3. `sc.credentials.edit("1000001", privilege_escalation="cisco")`

**Expected behavior**
The credential's privilege escalation setting should be set to Cisco 'Enable', and not throw an error

**System Information (please complete the following information):**
 - pytenable 4.1.7 with python 3.7 on Windows 10 64 bit
 - Tenable.sc 5.19

**Additional context**
Getting the credential details `sc.credentials.details("1000001")` from a credential with Cisco 'Enable' set via the GUI shows 'privilegeEscalation': "Cisco 'enable'"

### PR DESCRIPTION
**Pull request by nkoleske**
# Description

This change renames the allowed values for Tenable.sc Credential's privilege escalation from "cisco" to "Cisco 'enable'".

Fixes #618

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

# How Has This Been Tested?

1. Establish an authenticated Tenable.sc session
2. Create a credential entry
3. `sc.credentials.edit("1000001", privilege_escalation="Cisco 'enable'")`

**Test Configuration**:
* Python Version(s) Tested: 3.7.9
* Tenable.sc version 5.19

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by aseemsavio — CHANGES_REQUESTED** [review]
Hello @nkoleske, thanks for sending the PR. Please add tests to confirm behaviour.

**Comment by nkoleske** [comment]
I am not familiar with pytest. If you can recommend what type of test you are looking for and an example to reference I could try to write one. I took a look at tests/sc/test_credentials.py and didnt see anything that looked similar.

**Comment by SteveMcGrath** [comment]
This does seem to line up with the actual SC API.

CleanShot 2022-09-22 at 10 41 12

**Comment by aseemsavio** [comment]
Hey @nkoleske! pyTenable majorly uses [pytest](https://docs.pytest.org/en/7.1.x/) and [pytest-vcr](https://pypi.org/project/pytest-vcr/). Looking these libraries up would be beneficial. `pyTenable/tests/io/conftest.py` houses the test fixtures. You can refer to the files inside `pyTenable/tests/io/*` directory with a `test_` prefix as your examples for tests. Thanks.

**Review by aseemsavio — APPROVED** [review]

**Comment by inayathulla** [comment]
Changed will be merged in PR -> https://github.com/tenable/pyTenable/pull/639

**Pull request closed without merging**
