### PR TITLE
Feature/stream hook (for issue #305

### PR DESCRIPTION
**Pull request by mzpqnxow**
# Description

Implements feature requested in #305, please see that issue for full details

## Type of change

- [*] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have a standard workflow that exports ~50 (large) reports. I've tested it with the existing code, using `TenableIO.scans.export`. I tested these changes with that program and found the performance was the same and the results were the same

**Test Configuration**:
* Python 3.7

# Checklist:

- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation (Changed the docstring)
- [*] My changes generate no new warnings
- [*] New and existing unit tests pass locally with my changes

I have not added any new tests to the test-suite, I have only performed tests on real application code. The change is minimal and I don't see any ways it may be incompatible with any versions of cpython (2.x or 3.x) or any other Python interpreters for that matter

### CODE REVIEW

**Review by valliammal — APPROVED** [review]
I approved the changes, and it is adding facility of downloading stream of data, ok, good.

**Comment by levwais** [comment]
@valliammal  - please alter this PR to add tests which will test the added code. thanks.

**Review by mvalliammal — CHANGES_REQUESTED** [review]
Can you do add the test case for the stream_hook in the folder tests/io/test_scans.py?
As that is needed for doing the Merge

**Comment by mzpqnxow** [comment]
> Can you do add the test case for the stream_hook in the folder tests/io/test_scans.py?
> As that is needed for doing the Merge

Thank you @mvalliammal  and @levwais for looking at this, it's appreciated. I will get to the tests as soon as I can and then put an update here. Shouldn't be much work I just need to carve out some time to do it

**Comment by mzpqnxow** [comment]
@mvalliammal @levwais I added a test case for this 

https://github.com/tenable/pyTenable/pull/311/commits/8743939f04313faa13e916d8e506985c6a427359#diff-33a976499ebcbbd8c52cb41ba501e5d277da8b5badc55fff60ecac76907ad05bR435

I should mention that I set `TIO_TEST_STD_ACCESS`, `TIO_TEST_STD_SECRET` as well as `tests.io.conftest.SCAN_ID_WITH_RESULTS` to live values but still had problems running the tests, receiving the following:

```
ERROR    tenable.errors.PermissionError:errors.py:29 GET https://cloud.tenable.com/filters/scans/reports >> 2a8b8d8c7de435a435356989ff5bcdb7:401 This scanner, agent, or API key token does not appear to be related to any active containers on any sites and has been blacklisted.
```

I don't think this has anything to do with this PR, it seems more likely that I'm using `pytest` incorrectly. If you wouldn't mind validating on your side, I would be thankful. Hopefully there aren't any issues

Thanks again

**Review by mvalliammal — COMMENTED** [review]
The stream_hook function is getting called in the scans.py , so the def stream_hook needs to be present in that.  There is import statements inside a test function, which it should be in the top level. Do you want to comment on this?

**Comment by mzpqnxow** [comment]
Hey @mvalliammal thank you for  reviewing this

> The stream_hook function is getting called in the scans.py , so the def stream_hook needs to be present in that.

I think you may have misinterpreted the intention of this feature. `stream_hook` is an (optional) `callable` kwarg to  `tenable.io.scans.ScansAP.export()`, intended to be provided by the user/caller. The actual implementation of the callable can be whatever the user/caller would like, with the caveat that it must match the signature `(response: requests.Response, _fobj: TextIO, chunk_size: int = 1024)` and must have the logic to receive and return the data from the `requests.Response`

The use-case is described a little more clearly in #305, but the examples would be a callable that performs a custom status update to the console or provides some other custom logging action

In summary- the `stream_hook()` implementation should be opaque to `tenable.io.scans.ScansAP.export()`. The one included in the test is arbitrary, just to show that that the feature works

> There is import statements inside a test function, which it should be in the top level. Do you want to comment on this?

I usually define imports at the top level (per PEP8) but noticed that the existing tests for `ScansAP.export()` (at least as of the time I forked it) used function-level imports. I misinterpreted this as a convention used for pyTenable tests and then adhered to that. I will clean it up to use standard Python style

FYI- this was the existing test for `api.scans.export()` that I copied the import style from:

```
@pytest.mark.vcr()
def test_scan_export_bytesio(api):
    from io import BytesIO
    from tenable.reports.nessusv2 import NessusReportv2
    fobj = api.scans.export(SCAN_ID_WITH_RESULTS)
    assert isinstance(fobj, BytesIO)

    counter = 0
    for i in NessusReportv2(fobj):
        counter += 1
        if counter > 10:
            break
```

This test (and another test of the same method) has since been modified via some other commit, so I will clean it up to match the current convention. My mistake for not properly re-basing before adding the test

Thanks

**Pull request closed without merging**
